### ISSUE TITLE
GraphQL errors when passing sort parameters as separate variables

### ISSUE THREAD

**Issue by priyashantha** [silverstripe/silverstripe-graphql#583] opened 2024-05-08 07:46 UTC
### Module version(s) affected

4.3 and above

### Description

When the sort params are passed separately in variables a graphql error is triggered. When sort params are attached inside the query it works fine. There was no issue with "silverstripe/graphql" version 4.2.5. Issue happens on versions after that version i.e. 4.3.*, 5.*

![Screenshot 2024-05-08 at 1 11 37 PM](https://github.com/silverstripe/silverstripe-graphql/assets/6611682/be878692-370f-4f74-b7ca-33be8739f192)

### How to reproduce

Here is the query I'm using

```
query Pages($limit: Int, $sortBy: PageSortFields) {
  readPages(limit: $limit, sort: $sortBy) {
    edges {
      node {
        id
        title
      }
    }
  }
}
```

And the variables

```
{
    "sortBy": {
        "title": "DESC"
    }
}
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by lozcalver** [comment] 2024-05-08 08:02
Duplicate of https://github.com/silverstripe/silverstripe-graphql/issues/571

**Closed as completed by lozcalver** 2024-05-08 08:02 UTC
