### ISSUE TITLE
PageInfo is calculated vefore view permissions are checked

### ISSUE THREAD

**Issue by robingram** [silverstripe/silverstripe-graphql#260] opened 2020-04-08 01:22 UTC
The page info fields for count, next page and previous page are calculated _before_ the `canView` permissions are checked and so are inaccurate if the permissions remove any records from the results.

I can see how it might be inefficient to apply the permissions check to the entire record set before calculating the page info but the alternative is that page info isn't reliable.

**Comment by robbieaverill** [comment] 2020-04-08 02:47
This is an unfortunate side effect of the way that SilverStripe does its permission checking - since the checks can be dynamic we can't do them at the ORM level. Loading everything first and then filtering it is bad for memory consumption and DB query time, but it's the only thing we can really do at the moment, while we still support dynamic permission checks.

Related issue: https://github.com/silverstripe/silverstripe-framework/issues/2791

FYI the restfulserver module also has this issue.

**Comment by Cheddam** [comment] 2020-05-03 22:58
I'm going to close this as it's effectively a duplicate of the framework issue Robbie linked, it affects every module using pagination with permissions, and it's unlikely to be resolved prior to the next major version of Silverstripe CMS.

**Closed by Cheddam** 2020-05-03 22:58 UTC
